### ISSUE TITLE
pm2-dev does not restart server on file changes

### ISSUE THREAD

**Issue by soosap** [keymetrics/pm2-docker-alpine#22]
I have the following **docker-compose.yml** file:

```yaml
version: '3.2'

services:
  backend:
    image: keymetrics/pm2-docker-alpine:8
    ports:
      - 3000:3000
    working_dir: /var/www
    command: ["pm2-dev", "start", "process.yml"]
    volumes:
      - "../..:/var/www"
```

I am further using the following **process.yml** pm2 configuration:
```yaml
---
apps:
  - script: 'src/server.js'
    name: 'my-app'
    interpreter: 'babel-node'
    cwd: '/var/www'
```

The app starts alright. Unfortunately, it does not react to file changes. `docker exec -it <container_id> sh` 'ing into the container, I see that the file changes are propagated correctly. Yet, the server is not being restarted from within the container.

Trying the same thing outside a docker container works as expected. File changes trigger a restart with **pm2-dev**.
